"""remove tag_name from proposal_versions

Revision ID: 0a7e6e8fc12a
Revises: 770d5851ce1b
Create Date: 2025-11-27 16:22:53.397287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7e6e8fc12a'
down_revision: Union[str, Sequence[str], None] = '770d5851ce1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_versions', 'tag_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_versions', sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='版本标签 (如: v1.0 初稿)'))
    # ### end Alembic commands ###
