"""add assets table

Revision ID: 3973022e8f6c
Revises: f55901d96ef8
Create Date: 2025-11-24 13:31:42.441790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3973022e8f6c'
down_revision: Union[str, Sequence[str], None] = 'f55901d96ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False, comment='资源ID'),
    sa.Column('project_id', sa.UUID(), nullable=True, comment='关联项目ID'),
    sa.Column('filename', sa.String(), nullable=False, comment='原始文件名'),
    sa.Column('file_key', sa.String(), nullable=False, comment='MinIO存储键 (如: uploader/uuid.jpg)'),
    sa.Column('content_type', sa.String(), nullable=False, comment='MIME类型'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小 (bytes)'),
    sa.Column('url', sa.String(), nullable=False, comment='完整访问URL'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False, comment='上传人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    # ### end Alembic commands ###
