"""add version number and change type

Revision ID: 770d5851ce1b
Revises: 044182399ee0
Create Date: 2025-11-27 15:52:26.448523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770d5851ce1b'
down_revision: Union[str, Sequence[str], None] = '044182399ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum type first
    vct = sa.Enum('MAJOR', 'MINOR', name='versionchangetype')
    vct.create(op.get_bind())
    
    op.add_column('proposal_versions', sa.Column('change_type', vct, nullable=False, comment='修改类型'))
    op.add_column('proposal_versions', sa.Column('version_number', sa.String(), nullable=False, comment='版本号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_versions', 'version_number')
    op.drop_column('proposal_versions', 'change_type')
    
    # Drop Enum type
    sa.Enum(name='versionchangetype').drop(op.get_bind())
    # ### end Alembic commands ###
