"""remove project_id and url from assets

Revision ID: 91760ef222d8
Revises: 3973022e8f6c
Create Date: 2025-11-24 13:43:20.012334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91760ef222d8'
down_revision: Union[str, Sequence[str], None] = '3973022e8f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_project_id_fkey'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'url')
    op.drop_column('assets', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联项目ID'))
    op.add_column('assets', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False, comment='完整访问URL'))
    op.create_foreign_key(op.f('assets_project_id_fkey'), 'assets', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
