"""Initial tables

Revision ID: 9c0ec1b03043
Revises: 
Create Date: 2025-11-24 11:27:03.328060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0ec1b03043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户唯一ID'),
    sa.Column('username', sa.String(), nullable=True, comment='登录用户名'),
    sa.Column('password_hash', sa.String(), nullable=True, comment='加密后的密码哈希值'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'PLANNER', 'VENDOR', 'FINANCE', name='roletype'), nullable=False, comment='用户角色，决定权限范围'),
    sa.Column('team_id', sa.UUID(), nullable=True, comment='所属团队/门店ID (外键)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户是否激活，False表示已禁用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False, comment='线索唯一ID'),
    sa.Column('customer_name', sa.String(), nullable=False, comment='客户姓名'),
    sa.Column('phone', sa.String(), nullable=False, comment='手机号 (唯一标识，用于查重)'),
    sa.Column('wedding_date', sa.Date(), nullable=True, comment='预计婚期'),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='最低预算 (元)'),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='最高预算 (元)'),
    sa.Column('owner_id', sa.UUID(), nullable=True, comment='当前负责人ID (为空表示在公海)'),
    sa.Column('last_contact_at', sa.TIMESTAMP(), nullable=True, comment='最后跟进时间 (用于判定是否掉入公海)'),
    sa.Column('source', sa.String(), nullable=True, comment='线索来源 (如: 小红书, 转介绍, 门店自然到访)'),
    sa.Column('status', sa.Enum('NEW', 'CONTACTING', 'VISITED', 'INTENTIONAL', 'WON', 'LOST', 'PUBLIC_POOL', name='leadstatus'), nullable=False, comment='当前线索状态'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='项目唯一ID'),
    sa.Column('lead_id', sa.UUID(), nullable=False, comment='关联的线索ID (一对一)'),
    sa.Column('name', sa.String(), nullable=False, comment='项目名称 (如: 张伟&王芳婚礼)'),
    sa.Column('wedding_date', sa.Date(), nullable=False, comment='最终确定的婚期'),
    sa.Column('hotel_name', sa.String(), nullable=True, comment='举办酒店名称'),
    sa.Column('total_budget', sa.Numeric(precision=10, scale=2), nullable=True, comment='合同总金额 (元)'),
    sa.Column('stage', sa.Enum('PREPARING', 'DESIGNING', 'EXECUTING', 'COMPLETED', 'ARCHIVED', name='projectstage'), nullable=False, comment='当前项目阶段'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False, comment='审批单ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='关联项目ID'),
    sa.Column('requester_id', sa.UUID(), nullable=False, comment='申请人ID'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='审批人ID (处理后填充)'),
    sa.Column('type', sa.Enum('DISCOUNT', 'PAYMENT', 'REFUND', name='approvaltype'), nullable=False, comment='审批类型'),
    sa.Column('current_data', sa.JSON(), nullable=True, comment='申请时的快照数据 (如: 申请时的折扣金额、原价等)'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False, comment='当前状态'),
    sa.Column('audit_log', sa.Text(), nullable=True, comment='审批日志/备注 (如: 驳回原因)'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_items',
    sa.Column('id', sa.UUID(), nullable=False, comment='明细项ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目ID'),
    sa.Column('category', sa.String(), nullable=False, comment='分类 (如: 鲜花, 灯光, 人员, 搭建)'),
    sa.Column('name', sa.String(), nullable=False, comment='项目名称 (如: 进口红玫瑰, 主持人)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='销售单价 (对客价) - 策划师可见'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='成本单价 (内部价) - 仅Admin/Manager可见'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('supplier_id', sa.UUID(), nullable=True, comment='关联供应商ID (用于自动结算)'),
    sa.Column('is_locked', sa.Boolean(), nullable=True, comment='是否已锁定 (审批通过后不可修改)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_items')
    op.drop_table('approvals')
    op.drop_table('projects')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
