"""Add proposals and versions

Revision ID: f55901d96ef8
Revises: 9c0ec1b03043
Create Date: 2025-11-24 12:49:32.480367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55901d96ef8'
down_revision: Union[str, Sequence[str], None] = '9c0ec1b03043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False, comment='方案ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(), nullable=False, comment='方案名称 (如: 森系方案A)'),
    sa.Column('description', sa.Text(), nullable=True, comment='方案描述/备注'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SELECTED', 'ARCHIVED', name='proposalstatus'), nullable=False, comment='方案状态'),
    sa.Column('current_data', sa.JSON(), nullable=True, comment='当前编辑内容快照'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='版本ID'),
    sa.Column('proposal_id', sa.UUID(), nullable=False, comment='所属方案ID'),
    sa.Column('parent_version_id', sa.UUID(), nullable=True, comment='父版本ID'),
    sa.Column('snapshot_data', sa.JSON(), nullable=False, comment='版本全量快照数据'),
    sa.Column('change_log', sa.JSON(), nullable=True, comment="修改摘要 (如: {'diff': 'Deleted flower wall'})"),
    sa.Column('action_type', sa.Enum('AUTO_SAVE', 'MANUAL_SAVE', 'PUBLISH', name='versionactiontype'), nullable=False, comment='保存类型'),
    sa.Column('tag_name', sa.String(), nullable=True, comment='版本标签 (如: v1.0 初稿)'),
    sa.Column('editor_id', sa.UUID(), nullable=False, comment='修改人/版本提交人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='版本生成时间'),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['proposal_versions.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_versions')
    op.drop_table('proposals')
    # ### end Alembic commands ###
